project:
  type: website
  render:
    - "*.qmd"

website:
  title: "Warwick R-User Group"
  image: "media/logo_small_white.png"
  site-url: https://warwickrug.github.io
  description: "Warwick R-User Group's official website"
  # favicon: "favicon.png"
  reader-mode: true
  search: true
  repo-url: https://github.com/WarwickRUG/WarwickRUG.github.io
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - talks.qmd
    tools:
      - icon: mastodon
        href: https://fosstodon.org/@WarwickRUG
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/WarwickRUG/WarwickRUG.github.io
          - text: Report a Bug
            url:  https://github.com/WarwickRUG/WarwickRUG.github.io/issues
      - icon: calendar
        href: https://meetup.com/warwickrug/
      - icon: rss
        href: index.xml
format:
  html:
    theme: cosmo
    css: css/wrug.scss
    toc: true
    